CREATE TABLE `customer_infos` (
 `cu_id` int NOT NULL AUTO_INCREMENT,
 `branch_id` int(15) NOT NULL,
 `cu_type` varchar(30) NOT NULL,
 `customer_code` varchar(30) NOT NULL,
`cu_name` varchar(30) NOT NULL,
`cu_mobile` int(20) NOT NULL,
 `cu_email` varchar(20),
 `cu_address` varchar(100) NOT NULL,
 `cu_country` varchar(20),
 `cu_telephone` int(11),
 `cu_ac_no` varchar(30),
`cu_credit_limit` decimal(10,2),
`cu_discount_rate_p` decimal(6,2),
`cu_discount_rate_d` decimal(6,2),
`cu_discount_rate_o` decimal(6,2),
`cu_discount_rate_g` decimal(6,2),
`cu_bank_name` varchar(30),
`cu_branch_name` varchar(30),
`cu_description` varchar(100),
`reference_name` varchar(100),
`image` varchar(191),
 PRIMARY KEY (`cu_id`)
) ;
